#!/bin/bash

function error(){
	exec 1>&2
	help
	while [ "$#" -ge 1 ]; do echo -e "\e[31m$1\e[m"; shift; done
	exit 1
}

function warning(){
	while [ "$#" -ge 1 ]; do echo -e "\e[31m$1\e[m" >&2 ; shift; done
}

function set_args(){
	args=("$0" "$@")
}

function shift_args(){
	local n="$1"
	args=("${args[@]:$n}")
}