#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/str2str

function help(){
	abstract_help "chemblid2smiles" "id" "smiles" "ChEMBL ID" "SMILES"
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help
    -d, --default <value> | default value if not obtained
                          | default: ''
    -f, --force           | force normal termination even if not obtained

EOF
}

function parse_option(){
	# set default
	defaultValue=
	force=false

	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-d | --default)
			defaultValue="${args[2]}"
			shift_args 2
			;;
		-f | --force)
			force=true
			shift_args 1
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function errorhandling(){
	exitstatus="$?"
	echo "$defaultValue"
	if "$force"; then
		exit 0
	else
		exit "$exitstatus"
	fi
}

function process(){
	# $1: inpStr
	#
	local id xmldata smiles

	id="$1"
	if [[ "$id" =~ ^[0-9]+$ ]]; then
		id="CHEMBL${id}"
	fi
	if [[ ! "$id" =~ ^CHEMBL[0-9]+$ ]]; then
		error "ChEMBL ID is invalid: ${id}" || errorhandling
	fi

	# reference: https://www.ebi.ac.uk/chembl/api/data/docs
	xmldata=$(wget -qO- "https://www.ebi.ac.uk/chembl/api/data/molecule/${id}") || errorhandling
	smiles=`echo "$xmldata" |
				tr '\n' ' ' |
				sed -r 's/^.+(canonical_smiles.+canonical_smiles).+$/\1/' |
				sed -r 's/^[^>]+> *//' |
				sed -r 's/ *<[^<]+$//'`

	# print
	echo "$smiles"

}

main "$@"



