#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/str2str

function help(){
	abstract_help "len2len" "<unit1>" "<unit2>" "length in 'unit1'" "length in 'unit2'" "`option_help`"
}

function option_help(){
cat <<EOF
    -d, --delimiter <delimiter> | set delimiter
                                | default: ' '
    -f, --field <num>           | set target column number
                                | default: 1
    -s, --skip <num>            | set the title section
                                | default: 0
    --format <fmt>              | set format for print
                                | default: %.10g
    --from <unit> | a.u. / bohr / angstrom / nm / m
    --to <unit>   | same as above
EOF
}

function parse_option(){
	# set default
	delimiter=' '
	targetColumnNum=1
	headerEndLineNum=0
	fromunit=
	tounit=
	format='%.10g'
	
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-d | --delimiter)
			delimiter="${args[2]}"
			shift_args 2
			;;
		-f | --field)
			targetColumnNum="${args[2]}"
			shift_args 2
			;;
		-s | --skip)
			headerEndLineNum="${args[2]}"
			shift_args 2
			;;
		--format)
			format="${args[2]}"
			shift_args 2
			;;
		--from)
			fromunit="${args[2]}"
			shift_args 2
			;;
		--to)
			tounit="${args[2]}"
			shift_args 2
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
	
	if [ ! "$fromunit" ] ; then
		error "--from option is unspecified"
	fi
	if [ ! "$tounit" ] ; then
		error "--to option is unspecified" 
	fi
	
	# calc unit conversion factor
	fromunitfactor=`get_factor "$fromunit"`
	tounitfactor=`get_factor "$tounit"`
	factor=`awk -v format="${format}" "BEGIN {OFMT=format; print 1 / ${fromunitfactor} * ${tounitfactor} }"`
}

function get_factor(){
	# $1: unitname
	local unitname
	unitname="$1"
	case "$unitname" in
	au | a.u. | bohr | Bohr)
		factor=1
		;;
	A | angstrom | Angstrom)
		# 1[a.u.] = 0.529177210544[A] from https://en.wikipedia.org/wiki/Atomic_units
		factor="0.529177210544"
		;;
	nm)
		factor="( 0.529177210903 * 1e-1 )"
		;;
	m)
		factor="( 0.529177210903 * 1e-10 )"
		;;
	*)
		error "specified unit is invalid: ${unitname}"
		;;
	esac
	
	echo "$factor"
}

function process(){
	# $1: inpStr
	#
	local inpStr
	inpStr="$1"
	
	echo "$inpStr" |
		awk -v headerend="${headerEndLineNum}" \
			-v field="${targetColumnNum}" \
			-v delimiter="${delimiter}" \
			-v format="${format}" \
			-v factor="${factor}" \
			'BEGIN {
				FS="["delimiter"]"; OFS=delimiter; # set delimiter
				OFMT=format # format when printing
			}
			{
				if (NR > headerend && NF >= field) {
					# convert
					$field=sprintf(OFMT, $field*factor); print $0
				} else {
					# do nothing
					print $0
				}
			}'
	
}

main "$@"



