#!/bin/bash
set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/files2files

function help(){
	abstract_help "mden2csv" "<mden>" "<csv>" "Amber energy file" "csv file" ""
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_conversion_patt(){
	echo '{s/$/.csv/}'
}

function process(){
	# $1: inpFile
	#

	local mdenFile="$1"
	local mdenData=`cat "$mdenFile"`

	numLinePerFrame=`echo "$mdenData" |
						sed -r 's/ .+//' |
						sort |
						uniq |
						wc -l`

	sedN=`yes 'N;' |
			head -n $((${numLinePerFrame} - 1))`

	# convert and print
	echo "$mdenData" |
		sed -r 's/^[^ ]+ +//' | # remove leading Ln
		sed -r "{${sedN}s/\n/ /g}" | # convert to one line every frame
		sed -r 's/ +/,/g' # replace spaces with comma
}

main "$@"

