#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/void2file

function help(){
	abstract_help "mkmdin" "mdin" "Amber input file"
}

function comment_about_script(){
cat <<EOF
    generate mdin template

EOF
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help
    --emsemble <emsbl> | set emsemble: nve, nvt, npt
    --step <stp> | set calculation step: optimization, heatup, sampling
    --restart    | restart flag

EOF
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-O)
			parse_O_option
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_output_path(){
	# $1: inpStr
	echo 'mkmdin.mdin'
}

function process(){
	# $1: none
	#

}

main "$@"



