#!/bin/bash
set -eu

function help(){
cat <<EOF
mkresp
    generate prepin and frcmod (RESP/GAFF) from gaussian log file

usage:
    + mkresp glog
    +--- generate prepin and frcmod file in current directory
         recommended to prepare a dedicated directory in advance

option usage:
    -h, -help, --help | display this help

EOF
}

function error() {
	exec 1>&2
	help
	while [ "$#" -ge 1 ]; do echo -e "\e[31m$1\e[m"; shift; done
	exit 1
}

# ------------------------------------------------------------------

# parse options
while [ "$#" -gt 0 ] ;
do
	case "$1" in
	-h | -help | --help)
		help
		exit
		;;
	-*)
		error "unknown option: '$*'"
		;;
	*)
		break
		;;
	esac
done

# set input filename
if [ "$#" -gt 0 ]; then
	# if there are arguments
	glogFile="$1"
	# check
	if [ ! -f "$glogFile" ]; then
		error "mkresp: No such file: $glogFile"
	fi
else
	error "gaussian log file is not set"
fi

# ------------------------------------------------------------------
# remove trailing log(out) and make sure mol2 is attached
# sed -r 's/.(log|out)$/.mol2/': problem occurs if it does not end with 'log' or 'out'
mol2File=`echo "${glogFile}" | sed -r 's/.(log|out)$//' | sed -r 's/$/.mol2/'`

# get charge and multi
cm=`cat "$glogFile" |
	sed -r -n '/Charge.+Multiplicity/p' |
	head -n 1 |
	sed -r 's/[A-z =]+/ /g' |
	sed -r 's/^ //' |
	sed -r 's/ $//'`

charge="${cm% *}"
multi="${cm#* }"

antechamber -i "$glogFile" -fi gout -o "$mol2File" -fo mol2 -c resp -nc "$charge" -m "$multi" -at gaff
antechamber -i "$mol2File" -fi mol2 -o prepin -fo prepi
parmchk2 -i prepin -f prepi -o frcmod


