#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/files2files

function help(){
	abstract_help "mol22xyz" "mol2" "xyz" "Tripos mol2 file" "xyz file"
}

#function comment_about_script(){
#cat <<EOF
#
#EOF
#}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help

EOF
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-O)
			parse_O_option
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_conversion_patt(){
	echo '{s/.mol2$//; s/$/.xyz/}'
}

function process(){
	# $1: inpFile
	#
	local mol2File mol2Data
	local xyzData numAtom

	mol2File="$1"
	mol2Data=`cat "$mol2File"`

	# extract
	xyzData=`echo "$mol2Data" |
				sed -r -n '/^@<TRIPOS>ATOM/,/^@/p' | # extract from ATOM record to next record
				sed -r '/^@/d' |                     # delete record declaration line
				awk '{printf "%s   %s   %s   %s\n", $2, $3, $4, $5}' | # convert to xyz format
				sed -r 's/^([^0-9]+)[0-9]+ /\1 /' |  # If the atom name has a number, remove it
				sed -r 's/ -/-/g'` # adjust the number of spaces

	# set header
	numAtom=`echo "$xyzData" | wc -l`
	title="mol22xyz: from ${mol2File}: `date`"

	# print
	echo "$numAtom"
	echo "$title"
	echo "$xyzData"

}

main "$@"











