#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/str2file

function help(){
	abstract_help "name2sdf" "<name>" "<sdf>" "compound name" "MDL SDF file"
}

function comment_about_script(){
cat <<EOF
    Data is obtained by scraping from PubChem database

EOF
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help

EOF
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-O)
			parse_O_option
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_output_path(){
	echo 'name2sdf.sdf'
}

function process(){
	# $1: inpStr
	#
	local name encodedname sdfdata

	name="$1"
	encodedname=`echo -n "$name" | xxd -p | sed -r 's/(..)/%\1/g'`

	# get and print
	wget -qO- "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${encodedname}/record/SDF"

}

main "$@"



