#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/str2str

function help(){
	abstract_help "name2smiles" "<name>" "<smiles>" "compound name" "SMILES"
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help

EOF
}

function parse_option(){
	# set default

	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function process(){
	# $1: inpStr
	#
	local name encodedname cid smiles

	name="$1"
	encodedname=`echo -n "$name" | xxd -p | sed -r 's/(..)/%\1/g'`
	# cid=$(wget -qO- "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${encodedname}/cids/TXT")
	smiles=$(wget -qO- "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/${encodedname}/property/CanonicalSMILES/TXT")

	# print
	echo "$smiles"

}

main "$@"



