#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/files2files

function help(){
	abstract_help "pdb2xyz" "pdb" "xyz" "PDB: protein data bank file" "xyz file"
}

function comment_about_script(){
cat <<EOF
    If you want to process trajectory data with python,
    you should load mdcrd(s) directly into pytraj.

EOF
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help

EOF
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-O)
			parse_O_option
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_conversion_patt(){
	echo '{s/.pdb$//; s/$/.xyz/}'
}

function process(){
	# $1: inpFile
	#
	local pdbFile pdbData atomData
	local prexyzData minNumChar elementList
	local xyzData numAtom title

	pdbFile="$1"
	pdbData=`cat "$pdbFile"`
	atomData=`echo "$pdbData" | grep -e '^ATOM' -e '^HETATM'`

	prexyzData=`echo "$pdbData" |
					sed -r 's/^.{12}(.{4}).{14}(.{8})(.{8})(.{8}).*$/\1 \2 \3 \4/' |
					sed -r 's/ +/ /g' |
					sed -r 's/^ //'`

	# get valid element symbol
	minNumChar=`echo "$atomData" | awk '{print length($0)}' | sort -n | head -n 1`
	if [ "$minNumChar" -ge 77 ]; then
		elementList=`echo "$atomData" | sed -r 's/^.{76}(.{,2}).*/\1/'`
		xyzData=`paste -d ' ' <(echo "$elementList") <(echo "$prexyzData" | sed -r 's/^[^ ]+//')`
	else
		xyzData="$prexyzData"
	fi

	# set header
	numAtom=`echo "$xyzData" | wc -l`
	title=`pdb2xyz: from ${pdbFile}: `date``

	# print
	echo "$numAtom"
	echo "$title"
	echo "$xyzData"
}

main "$@"











