#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/files2files

function help(){
	abstract_help "pdb2xyz" "<pdb>" "<xyz>" "PDB: protein data bank file" "xyz file"
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help

EOF
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-O)
			parse_O_option
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_conversion_patt(){
	echo '{s/.pdb$//; s/$/.xyz/}'
}

function process(){
	# $1: inpFile
	#
	local pdbFile
	pdbFile="$1"
	
	cat "$pdbFile" |
		grep ATOM |
		sed -r 's/^.{12}(.{4}).{14}(.{8})(.{8})(.{8}).*$/\1 \2 \3 \4/' |
		sed -r 's/ +/ /g' |
		sed -r 's/^ //' |
		sed -r 's/ /\n/1' |
		sed -r '1~2s/[0-9]//g' |
		sed -r '{N;s/\n/ /}'
	
	# HETATMの扱いを再考
	# 元素記号がこのままでは使えないので修正すること
}

main "$@"











