#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/str2file

function help(){
	abstract_help "pdbid2pdb" "id" "pdb" "PDB ID" "PDB"
}

function comment_about_script(){
cat <<EOF
    Data is obtained by scraping from RCSB PDB database

EOF
}

function option_help(){
cat <<EOF
    -h, -help, --help | display this help

EOF
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-O)
			parse_O_option
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_output_path(){
	# $1: inpStr
	local id
	id="$1"

	echo "${id}.pdb"
}

function process(){
	# $1: inpStr
	#
	local id

	id="$1"

	# 出力先の設定について考え直す
	# 取得できなかった場合のエラーハンドリングについて仕様を詰める

	# get and print
	wget -qO- "https://files.rcsb.org/download/${id}.pdb"

}

main "$@"



