#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/utl/common.sh

function help(){
cat <<EOF
rmexcept
    remove all files in the current directory except the specified files
    this does not remove hidden files

usage:
    + rmexcept [option] <file>
    +--- remove everything except <file>

option usage:
    -h, -help, --help | display this help
    -r, -R, --recursive | remove directories and their contents recursively

EOF
}


option=
while [ "$#" -gt 0 ]
do
	case "$1" in
	-r | -R | --recursive)
		option="-r"
		shift 1
		;;
	-h | -help | --help)
		# TODO
		# help
		exit
		;;
	-*)
		error "unknown option: '$1'"
		;;
	*)
		break
		;;
	esac
done

notDeleteFiles=("$@")
evacuatedFiles=()

for i in `seq 0 "$((${#notDeleteFiles[@]} - 1))"`
do
        f="${notDeleteFiles[i]}"
        f2=`mktemp -p . .XXXXXX`
        evacuatedFiles+=("$f2")
        mv "$f" "$f2"
done

# redundant processing
shopt -u dotglob

# If set -e is used, rm * may fail, so do not specify it.
set +e
rm ${option} *
set -e

for i in `seq 0 "$((${#notDeleteFiles[@]} - 1))"`
do
        f="${notDeleteFiles[i]}"
        f2="${evacuatedFiles[i]}"
        mv "$f2" "$f"
done










