#!/bin/bash

set -eu
SCRIPT_DIR=$(cd $(dirname $0); pwd)
source "${SCRIPT_DIR}"/abstract/files2files

function help(){
	abstract_help "xyz2pdb" "<xyz>" "<pdb>" "xyz file" "PDB: protein data bank" ""
}

function parse_option(){
	while [ "${#args[@]}" -gt 1 ]
	do
		case "${args[1]}" in
		-h | -help | --help)
			help
			exit
			# shift_args 1
			;;
		-*)
			error "unknown option: '${args[1]}'"
			;;
		*)
			break
			;;
		esac
	done
}

function get_default_conversion_patt(){
	echo '{s/.xyz$//; s/$/.pdb/}'
}

function process(){
	# $1: inpFile
	#
	local xyzFile="$1"
	local xyzContents=`cat "$xyzFile"`

	# convert and print
	echo "$xyzContents" |
			sed -r '1,2d' | # delete the header
			nl | # set serial number of atoms
			xargs printf "ATOM  %5d %-4s R01     1    %8.3f%8.3f%8.3f\n" # print

}

main "$@"











