#!/bin/bash

function error(){
	help >&2
	while [ "$#" -ge 1 ]; do echo -e "\e[31m$1\e[m" >&2 ; shift; done
	exit 1
}

function warning(){
	while [ "$#" -ge 1 ]; do echo -e "\e[31m$1\e[m" >&2 ; shift; done
}

function set_args(){
	args=("$0" "$@")
}

function shift_args(){
	local n="$1"
	args=("${args[@]:$n}")
}

function initialize_output(){
	exec {ChemScript_common_stdout_fd}>&1
}
# execute to initialize
initialize_output

function set_output(){
	# set_output [--append] <output>
	# if output is -, then print to stdout
	local append=false
	local output=
	if [ "$1" = "--append" ]; then
		append=true
		output="$2"
	else
		output="$1"
	fi

	if [ "$output" = "-" ]; then
		exec >&${ChemScript_common_stdout_fd}
	elif "$append" ; then
		exec >> "$output"
	else
		exec > "$output"
	fi
}


