#!/bin/bash

source "${SCRIPT_DIR}"/abstract/common

#flowchart
#check -O option
#	-O -: stdout
#	-O file: out to file
#	-O subpatt: out to file which name is decided by subpatt
#check input
#	pipe:
#		if -O subpatt, error exit
#		if -O file, then IO follow it
#		else: stdout
#	ps sub(any):
#		if -O subpatt, error exit
#		if -O file, then IO follow it
#		else: stdout
#	file(all):
#		if -O subpatt and there is even one "-" as input, error exit
#		if -O file and -O -, then IO follow it
#		if [-t1] is true, out to file according to the default patt
#		else: stdout
#
#

function abstract_help(){
	local cmd="$1"
	local inp="$2"
	local out="$3"
	local inpDetail="$4"
	local outDetail="$5"
	local optionUsage="$6"
cat <<EOF
${cmd}
    convert ${inp} to ${out}
    ${inp}: ${inpDetail}
    ${out}: ${outDetail}
    implementation of files2files

usage:
    + ${cmd} ${inp}
    +--- convert ${inp} to ${out} and save to ${out} with an appropriate name automatically
    |
    + ${cmd} ${inp} > ${out}
    +--- save to the ${out} file
    |
    + ${cmd} ${inp} | <COMMAND>
    +--- input to the next command
    |
    + <COMMAND> | ${cmd}
    +--- convert the entered ${inp} data and print to stdout
    |
    + ${cmd} <(<COMMAND>)
    +--- if input by process substitution, print to stdout
    |
    + ${cmd} -O ${out} ${inp}
    + ${cmd} -O - ${inp}
    +--- if you want to force the output destination, use the -O option
    |
    + ${cmd} -O 's/BEF/AFT/' ${inp}1 ${inp}2 ...
    +--- it is also possible to specify multiple input files.
         if you specify a sed subcommand to the -O option,
         you can output with your favorite file name.

option usage:
    -h, -help, --help | display this help
${optionUsage}

EOF
}

function parse_args(){
	# parse -O option
	local outputDestIsForced=
	local forcedOutputDestType= # unforced, stdout, pattfile, fixfile
	local forcedOutputDest=
	local forcedOutputDestPatt=
	if [ "${#args[@]}" -ge 2 ] && [ "${args[1]}" = "-O" ]; then
		outputDestIsForced=true
		local value="${args[2]}"
		if [ "$value" = "-" ]; then
			forcedOutputDestType=stdout
			forcedOutputDest="-"
		elif echo "" | sed -r "$value" > /dev/null 2> /dev/null; then
			forcedOutputDestType=pattfile
			forcedOutputDestPatt="$value"
		else
			forcedOutputDestType=fixfile
			forcedOutputDest="$value"
		fi
		shift_args 2
	else
		outputDestIsForced=false
		forcedOutputDestType=unforced
		forcedOutputDest="-"
	fi

	# parse options of implemented script
	parse_option

	# parse inp data and out
	inpFiles=("${args[@]:1}")
	numInpFile="${#inpFiles[@]}"
	if [ "$numInpFile" = 0 ]; then
		# if there are no remaining arguments

		if [ ! -t 0 ]; then
			# Without this judgment, it will wait if there is no pipe input and no argument input.
			# from pipe
			inpFiles=("-")
			numInpFile=1

			case "$forcedOutputDestType" in
			unforced | stdout)
				outIsFile=false
				outputs=("-")
				;;
			pattfile)
				error "cannot proceed with pipe input and replacement pattern specification"
				;;
			fixfile)
				outIsFile=true
				outputs=("$forcedOutputDest")
				;;
			esac
		else
			error "inp data is not set"
		fi
	else
		local pipeInInp=false
		local psSubInInp=false
		while [ "${#args[@]}" -gt 1 ]
		do
			local _inp="${args[1]}"
			if [ "$_inp" = "-" ]; then
				# if input from pipe
				pipeInInp=true

			elif [[ "$_inp" =~ ^/dev/fd ]]; then
				# if input by process substitution
				psSubInInp=true
			fi
			shift_args 1
		done

		outputs=()
		if "$pipeInInp" || "$psSubInInp"; then
			case "$forcedOutputDestType" in
			unforced | stdout)
				outIsFile=false
				for i in `seq "$numInpFile"`; do outputs+=("-"); done
				;;
			pattfile)
				error "cannot proceed with replacement pattern specification and pipe input or ps sub"
				;;
			fixfile)
				outIsFile=true
				for i in `seq "$numInpFile"`; do outputs+=("$forcedOutputDest"); done
				;;
			esac
		else
			# all input is file
			case "$forcedOutputDestType" in
			unforced)
				if [ -t 1 ]; then
					# out to file which is named by default patt
					outIsFile=true
					local patt=`get_default_conversion_patt`
					for i in `seq 0 "$(($numInpFile-1))"`; do outputs+=(`echo "${inpFiles[i]}" | sed -r "$patt"`); done

				else
					outIsFile=false
					for i in `seq "$numInpFile"`; do outputs+=("-"); done

				fi
				;;
			stdout)
				outIsFile=false
				for i in `seq "$numInpFile"`; do outputs+=("-"); done
				;;
			pattfile)
				outIsFile=true
				for i in `seq 0 "$(($numInpFile-1))"`; do outputs+=(`echo "${inpFiles[i]}" | sed -r "$forcedOutputDestPatt"`); done
				;;
			fixfile)
				outIsFile=true
				for i in `seq "$numInpFile"`; do outputs+=("$forcedOutputDest"); done
				;;
			esac
		fi
	fi

}

#function parse_option(){
#	# parse option from "${args[@]}"
#}

#function get_default_conversion_patt(){
#	echo '{s/out$//; s/$/csv/}'
#}

#function process(){
#	# $1: inpFile
#	# limit 'cat "$1"' to one execution because of cat -
#}

function main(){
	set_args "$@"
	parse_args

	for i in `seq 0 "$(($numInpFile-1))"`
	do
		local inpFile="${inpFiles[i]}"
		local output="${outputs[i]}"
		set_output "$output"

		# convert file
		process "$inpFile"
	done
}




